### ISSUE TITLE
ページネーションについて

### ISSUE THREAD

**Issue by menyuu** [banken-paopao/nagano_cake#54]
### ページネーションについて
kaminari等を導入しようと思います。
必要な個所はコメントで共有していきましょう。

**Comment by menyuu** [comment]
itemのindexページ

**Comment by yukiya0330** [comment]
admin/homes/top
admin/customers/index

**Comment by yukiya0330** [comment]
admin/orders/history.html.erb

**Comment by ttymryo** [comment]
public/orders/index

**Comment by menyuu** [comment]
ページネーション完了
